### ISSUE TITLE
Перевыпуск сертификата

### ISSUE THREAD

**Issue by iamrustamov** [ssharkexe/telegram-nginx-docker-webhook#3]
Привет! Думал смогу PR оформить, но увы нет такой возможности. 

Предлагаю добавить информацию о продлении сертификата в README

Поздравляю, сертификат выпущен (на 3 месяца)! Для продления воспользуйтесь командой:
```
docker compose run --rm  certbot renew
```

**Comment by evgeniy-kolmak** [comment]
Тебе стоит быть внимательней

**Comment by iamrustamov** [comment]
> Тебе стоит быть внимательней

Стоило дочитать до конца :)
